### ISSUE TITLE
Issue on page /README.html

### ISSUE THREAD

**Issue by Holly-Transport** [worldbank/template#12]
I've noticed twice that to activate GitHub actions, first the user needs to go to the "Actions" menu in settings and check the option for "Read and write permissions". It'd be a good idea to add this to the instructions, because otherwise it may not be intuitive :-) 
![image](https://user-images.githubusercontent.com/4492990/229004341-84b8afdf-3005-4dd4-a4b8-7b7ad7fbb6d6.png)

**Comment by g4brielvs** [comment]
Closed by 56e9c95486bfee662ce1747d37beeb5ed0163fa7.
