### ISSUE TITLE
Failing to build on private repositories

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/template#18]
The [template](https://worldbank.github.io/template/README.html) depends on [GitHub Actions](https://github.com/features/actions). However, the [World Bank](https://github.com/worldbank) uses a legacy GitHub plan that doesn't allow the feature on private repositories. As a consequence, [template](https://worldbank.github.io/template/README.html) is failing on private repositories. Alternatively, GitHub Actions is available on **public** repositories.

> GitHub Actions is not available for private repositories on legacy per-repository billing plans. Review your pricing plan to get access to this feature.

**Comment by g4brielvs** [comment]
@Holly-Transport This [workflow failed](https://github.com/worldbank/morocco-economic-monitor/actions/runs/5404112936) is due to this issue.

**Comment by g4brielvs** [comment]
@dmatekenya This [workflow](https://github.com/worldbank/DECAT_HH_Geovariables/actions) failed because of this issue.

**Comment by kbjarkefur** [comment]
@g4brielvs , happy to help on this, but I will let @bpstewar answer regarding current or future status of the legacy billing plan of the `worldbank` account.

Let me know if I can support in any other way.

**Comment by g4brielvs** [comment]
Solved by https://github.com/worldbank/.github/issues/3.
