### ISSUE TITLE
Typos on Template 

### ISSUE THREAD

**Issue by danielgils** [worldbank/template#20]
Typos on section 2.1: 
- It says "**_Pyhton_** API wrapper class created to **_faciliate_** the usage of the [...]". 
- It says: "Note that contrary to the [previous example](https://worldbank.github.io/template/notebooks/world-bank-api.html), the method **_expets_** a list of country names and converts them [...]".
Typos on section 3.1:
- It says "Please note that .env must never be commited/versioned (for example, to GitHub) and should **_[be]_** ignored on .gitignore."

**Comment by g4brielvs** [comment]
@danielgils Thanks you **so** much for contributing to the template.

**Comment by g4brielvs** [comment]
@danielgils Thank you **so** much for your contribution 🙏!
