### ISSUE TITLE
Add gallery

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/template#25]
Thanks to positive response and adoption by the community, it's time to add a gallery of projects.

**Comment by Lymah123** [comment]
I am interested.

**Comment by g4brielvs** [comment]
> I am interested.

Hi @Lymah123! Thank you for your interest. Please free feel to describe what you have in mind.

**Comment by Lymah123** [comment]
Hi @g4brielvs! I was thinking of something like adding a description , image and link to the image gallery topic so that developers can easily learn about it.
