### ISSUE TITLE
When creating a new repo from template and selecting "include all branches" two additional pull requests created.

### ISSUE THREAD

**Issue by Holly-Transport** [worldbank/template#58]
<img width="837" alt="image" src="https://github.com/user-attachments/assets/1e106a1a-cb30-4000-85f8-8ab1c818b9e1">

How should we advise users to address these, or is there something we need to adjust in the template?

**Comment by g4brielvs** [comment]
Thanks! To clarify, no pull requests are being created, but the branches were indeed included. By default, branches should not be included. As explained in the [GitHub Docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template#about-repository-templates):

> Optionally, to include the directory structure and files from all branches in the template, and not just the default branch, select Include all branches.

**Comment by Holly-Transport** [comment]
Thank you! When I set up the repo without including the branches, it doesn't work:

(1) Setting up repo without branches:
<img width="597" alt="image" src="https://github.com/user-attachments/assets/b91a136b-c40a-44ba-968a-f1705fc62733">

(2) gh-pages then doesn't appear as a branch:
<img width="784" alt="image" src="https://github.com/user-attachments/assets/17791843-f573-4d53-bfd7-5c7a8269dede">

(3) And actions stalls:
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/3fc06742-923c-4290-b8d0-a1505995ba16">
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/47417866-7fc0-4c81-946c-b87efba35785">

But when I include branches, it does. Advice most appreciated.

**Comment by g4brielvs** [comment]
Please you may refer to [step 2](https://worldbank.github.io/template/README.html#enable-github-actions-and-github-pages).
