### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/template#6]
The [template](https://github.com/worldbank/template) uses the [World Bank Master Community License Agreement](https://github.com/worldbank/template/blob/main/LICENSE.md). All repositories generated from it will therefore use the same license. It is unclear, however, if this license is appropriate, considering it requires to be signed and countersigned to become effective. Also, it is unclear if we can use common [open source licenses](https://choosealicense.com/) as World Bank staff.

**Comment by g4brielvs** [comment]
Looping in @andresfchamorro @trevmon28.

**Comment by KPGeo** [comment]
This is the license authorized we are authorized to use. A more detailed explanation is available. Other open-source licenses are not formally permitted.
